Feature: Add kaigara to OpenDAX compose, integrate Sonic
openware/opendax pull request #283
Opened 2021-02-17 16:53 UTC by akulakovaa

2021-02-17 22:04 UTC, vshatravenko requested changes

2021-02-17 22:04 UTC, vshatravenko commented on templates/secrets.yaml.erb
> +secrets:
I can only see barong in here, has there been any progress?

2021-02-19 07:52 UTC, calj commented on templates/secrets.yaml.erb
> +        secret_key_base: faiba2shei0Ae5gahCh4aipoh3meyaFi
This secret must be generated

2021-02-19 07:52 UTC, calj commented on templates/secrets.yaml.erb
> +        secret_key_base: faiba2shei0Ae5gahCh4aipoh3meyaFi
This secret must be generated

2021-02-19 08:08 UTC, calj commented on templates/secrets.yaml.erb
> +        jwt_private_key: <%= @barong_private_key %>
here we need a specific key for peatio

2021-02-19 08:09 UTC, calj commented on templates/secrets.yaml.erb
> +        database_host: <%=  @config['database']['host'] %>
here we need public keys of components:
```
peatio_public_key
barong_public_key
sonic_public_key
```

2021-02-24 08:43 UTC, dpatsora commented on templates/secrets.yaml.erb
> +        captcha_type: <%= @config['captcha']['type'] %>
captcha_id: <%= ssl_helper('http') %>://<%= @config['app']['subdomain'] %>.<%= @config['app']['domain'] %>

2021-02-24 08:43 UTC, dpatsora commented on templates/secrets.yaml.erb
> +        barong_api_cors_origins: https://2-6-stable.openfinex.io
barong_api_cors_origins: <%= ssl_helper('http') %>://<%= @config['app']['subdomain'] %>.<%= @config['app']['domain'] %>

2021-06-17 16:20 UTC, merged